ctrl+enter script-binding playlistmanager/openmenu
ctrl+LEFT playlist-prev
ctrl+RIGHT playlist-next

Ctrl+f     script-binding quality_menu/video_formats_toggle
Alt+f script-binding quality_menu/audio_formats_toggle

Alt+c run sh -c 'echo -e "${path}"| wl-copy'
ctrl+I run "/bin/sh" "-c" 'foot ~/dox/dmenuytutils/getytcomments "${path}"'
