ytdl-format=bestvideo*[height<=?720][fps<=?30][vcodec!=?vp9]+bestaudio/best
ytdl-raw-options = format-sort="proto"
ytdl-raw-options-append="extractor-args=youtube:player-client=default"
#ytdl-raw-options=cookies-from-browser=firefox:/home/evan/.config/librewolf/librewolf
#ytdl-raw-options=cookies=/home/evan/dox/cookies-youtube-com.txt,extractor-args=youtube:player_client=default
save-watch-history
write-filename-in-watch-later-config
save-position-on-quit
osc=no
cookies=yes

volume=70
network-timeout=30


# P loadlist "~/.config/mpv/playlists.txt" append 0
[windowed] 
fullscreen=no
