#!/usr/bin/env bash

sed -i -e "s/rootcolor=.*/rootcolor=0x354B45FF /" -e \
	"s/bordercolor=.*/bordercolor=0x171C1DFF /"\
	-e "s/dropcolor=.*/dropcolor=0x22B586FF /"\
	-e "s/splitcolor=.*/splitcolor=0x2DFCD0FF /"\
	-e "s/focuscolor=.*/focuscolor=0x47808BFF /"\
	-e "s/maximizescreencolor=.*/maximizescreencolor=0x22B586FF /"\
	-e "s/urgentcolor=.*/urgentcolor=0x2DFCD0FF /"\
	-e "s/scratchpadcolor=.*/scratchpadcolor=0x14B582FF /"\
	-e "s/globalcolor=.*/globalcolor=0x5CCFABFF /"\
	-e "s/overlaycolor=.*/overlaycolor=0xCAFEF3FF /" ~/.config/mango/config.conf
