;;; tokyonight-night-theme.el --- TokyoNight Night-*- lexical-binding: t -*-
;;; Commentary:
;;; Code:

(eval-and-compile
  (unless (and (fboundp 'require-theme)
               load-file-name
               (equal (file-name-directory load-file-name)
                      (expand-file-name "themes/" data-directory))
               (require-theme 'tokyonight-themes t))
    (require 'tokyonight-themes))
      (tokyo-bg-dark "#1f2335")
      (tokyo-bg-hl "#292e42")
      (tokyo-fg "#c0caf5")
      (tokyo-fg-1 "#a9b1d6")
      (tokyo-fg-2 "#3b4261")
      (tokyo-white "#ffffff")
      (tokyo-black "#414868")
      (tokyo-comment "#565f89")
      (tokyo-dark "#545c7e")
      (tokyo-dark+1 "#737aa2")
      (tokyo-blue-1 "#394b70")
      (tokyo-blue "#3d59a1")
      (tokyo-blue+1 "#7aa2f7")
      (tokyo-blue+2 "#2ac3d3")
      (tokyo-blue+3 "#0db9d7")
      (tokyo-blue+4 "#89ddff")
      (tokyo-blue+5 "#b4f9f8")
      (tokyo-cyan "#7dcfff")
      (tokyo-magenta "#bb9af7")
      (tokyo-magenta+1 "#ff007c")
      (tokyo-purple "#9d7cd8")
      (tokyo-orange "#ff9e64")
      (tokyo-yellow "#e0af68")
      (tokyo-green "#9ece6a")
      (tokyo-teal-1 "#41a6b5")
      (tokyo-teal "#1abc9c")
      (tokyo-teal+1 "#73daca")
      (tokyo-red-1 "#db4b4b")
      (tokyo-red "#f7768e"))
 
  (defvar tokyonight-night-palette
    '((bg "#1a1b26")
      (bg-dark "#16161e")
      (bg-dark1 "#0c0e14")
      (bg-hl "#292e42")
      (blue0 "#3d59a1")
      (blue "#7aa2f7")
      (blue1 "#2ac3de")
      (blue2 "#0db9d7")
      (blue5 "#89ddff")
      (blue6 "#b4f9f8")
      (blue7 "#394b70")
      (comment "#565f89")
      (cyan "#7dcfff")
      (dark3 "#545c7e")
      (dark5 "#737aa2")
      (fg "#c0caf5")
      (fg-dark "#a9b1d6")
      (fg-gutter "#3b4261")
      (green "#9ece6a")
      (green1 "#73daca")
      (green2 "#41a6b5")
      (magenta "#bb9af7")
      (magenta2 "#ff007c")
      (orange "#ff9e64")
      (purple "#9d7cd8")
      (red "#f7768e")
      (red1 "#db4b4b")
      (teal "#1abc9c")
      (terminal-black "#414868")
      (yellow "#e0af68"))
    "TokyoNight night palette.")

  (tokyonight-themes-define-theme tokyonight-night dark "TokyoNight Night"))

(provide 'tokyonight-night-theme)
;;; tokyonight-night-theme.el ends here
