[main]
font=JetBrainsMono-Light:size=10

dpi-aware=yes
pad=5x0

[colors]
foreground=bbc2cf
background=242730
alpha=0.8

# Cursor colors
cursor=242730 aabbbd

# The basic 16 colors
# black
#[colors-dark]
regular0=2a2e38 #2a2e38
regular1=ff665c #ff665c
regular2=7bc275 #7bc275
regular3=fcce7b #fcce7b
regular4=51afef #51afef
regular5=C57BDB #C57BDB
regular6=5cEfFF #5cEfFF
regular7=DFDFDF #DFDFDF

#[colors-light]
bright0=484854 #484854
bright1=ff665c #ff665c
bright2=99bb66 #99bb66
bright3=ecbe7b #ecbe7b
bright4=51afef #51afef
bright5=c678dd #c678dd
bright6=46D9FF #46D9FF
bright7=bbc2cf #bbc2cf
