[main]
font=JetBrainsMono-Light:size=10

dpi-aware=yes
pad=5x0

[colors]
foreground=B2BFC1
background=040E0C
#alpha=0.8

# Cursor colors
cursor=081A16 B2BFC1

# The basic 16 colors
# black
#[colors-dark]
regular0=354B45
regular1=2DFCD0
regular2=22B586
regular3=24B0C7
regular4=3B7695
regular5=168B6B
regular6=2E6A77
regular7=889B9F

#[colors-light]
bright0=5F6C6F
bright1=2DFCD0
bright2=22B586
bright3=24B0C7
bright4=3B7695
bright5=2D8B71
bright6=2E6A77
bright7=889B9F
