[main]
font=JetBrainsMono-Light:size=10

dpi-aware=yes
pad=5x0

[colors]
foreground=bbc2cf
background=242730
alpha=0.8

# Cursor colors
cursor=242730 aabbbd

# The basic 16 colors
# black
#[colors-dark]
regular0=000000 #000000
regular1=ff2c70 #ff2c70
regular2=82DD61 #82DD61
regular3=fad000 #fad000
regular4=4F93FF #4F93FF
regular5=FF54A4 #FF54A4
regular6=C580FF #C580FF
regular7=DFDFDF #DFDFDF

#[colors-light]
bright0=5c5c61 #5c5c61
bright1=e33937 #e33937
bright2=70DC48 #70DC48
bright3=fad000 #fad000
bright4=6943ff #6943ff
bright5=fb94ff #fb94ff
bright6=D54AFF #D54AFF
bright7=ffffff #ffffff
